
permalink: /:year:month:day/:title
url: https://www.michaeleisemann.com #Your url here
base url:
# variables
name: Michael Eisemann's Personal Site
description: You've made it this far, why not read more?
google_verification: null
port: 4002

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE", "log.txt", "changed"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter_opts:
        disable : true

plugin:
    - jekyll-feed

feed:
    path: feed.xml
